# This is a basic workflow to help you get started with Actions

name: Validate List

on:
  push:
    branches-ignore: 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Update List and validate
        run: node actions/createList.js
